/**
 * Repository 生成器
 * 根据 ResourceDefinition 生成 Repository 类
 */

import { ResourceDefinition } from '../types/resource.types';
import * as path from 'path';
import * as fs from 'fs';

export class RepositoryGenerator {
  /**
   * 生成 Repository 代码
   */
  generateRepository(resource: ResourceDefinition): string {
    const className = this.toPascalCase(resource.name);
    const entityName = resource.prismaModel;
    const modelName = resource.pluralName || `${resource.name}s`;

    // 生成 defaultSelect
    const defaultSelect = this.generateDefaultSelect(resource);

    // 根据字段自动生成常用方法
    const autoGeneratedMethods = this.generateAutoMethods(resource, entityName);

    return `import { Injectable } from '@nestjs/common';
import { PrismaService } from '@/prisma/prisma.service';
import { BaseCrudRepository } from '@/common/repositories/base-crud.repository';
import { ${entityName} } from '@prisma/client';

/**
 * ${resource.description || `${className} Repository`}
 * 
 * 数据访问层，负责与数据库交互，提供细粒度的 ORM 操作方法。
 * 
 * 本 Repository 继承 BaseCrudRepository，已提供以下细粒度方法：
 * - create(data, options?) - 创建单条记录
 * - findOne(id, options?) - 根据 ID 查询单条记录
 * - findByIds(ids, options?) - 根据多个 ID 查询记录
 * - findMany(options?) - 根据条件查询多条记录
 * - findByCondition(where, options?) - 根据条件查询（更明确的接口）
 * - findAll(pagination?, options?) - 分页查询
 * - findFirst(options?) - 根据条件查询第一条记录
 * - update(id, data, options?) - 更新单条记录
 * - delete(id) - 删除单条记录
 * - deleteMany(ids) - 批量删除
 * - count(where?) - 统计数量
 * - exists(id) - 检查记录是否存在
 * - createMany(data[], options?) - 批量创建
 * - updateMany(ids, data, options?) - 批量更新
 * 
 * Service 层应该使用这些 Repository 方法来组装业务逻辑，而不是直接使用 ORM。
 * 
 * 根据 Schema 字段自动生成的方法：
 * - 如果存在 status 字段（string 类型）：自动生成 updateStatus(id, status) 方法
 * - 如果存在 isActive 字段（boolean 类型）：自动生成 activate(id), deactivate(id), toggleActive(id) 方法
 * - 如果存在 deletedAt 字段（date 类型）：自动生成 softDelete(id), restore(id), findActive() 方法
 * - 如果存在 isDeleted 字段（boolean 类型）：自动生成 softDelete(id), restore(id), findActive() 方法
 * - 如果存在 enabled 字段（boolean 类型）：自动生成 enable(id), disable(id) 方法
 * 
 * 如果需要添加更多自定义的细粒度方法，可以在此类中扩展：
 * \`\`\`typescript
 * async findByStatus(status: string) {
 *   return this.findByCondition({ status });
 * }
 * \`\`\`
 */
@Injectable()
export class ${className}Repository extends BaseCrudRepository<
  ${entityName},
  any,
  any
> {
  protected readonly defaultPageSize = ${resource.defaultPageSize || 10};
  protected readonly defaultSelect = ${defaultSelect} as const;

  constructor(private readonly prisma: PrismaService) {
    super();
  }

  protected getModelDelegate() {
    return this.prisma.${resource.name};
  }
${autoGeneratedMethods}
}
`;
  }

  /**
   * 生成 defaultSelect
   */
  private generateDefaultSelect(resource: ResourceDefinition): string {
    const fields = resource.fields.filter(
      (f) => f.includeInList !== false && f.name !== 'password',
    );

    if (resource.defaultSelect) {
      return JSON.stringify(resource.defaultSelect, null, 2);
    }

    const select: Record<string, boolean> = {
      id: true,
    };

    fields.forEach((field) => {
      if (field.type !== 'relation') {
        select[field.name] = true;
      }
    });

    // 添加时间戳字段（如果存在）
    if (resource.fields.some((f) => f.name === 'createdAt')) {
      select.createdAt = true;
    }
    if (resource.fields.some((f) => f.name === 'updatedAt')) {
      select.updatedAt = true;
    }

    return JSON.stringify(select, null, 2);
  }

  /**
   * 根据字段自动生成常用方法
   */
  private generateAutoMethods(resource: ResourceDefinition, entityName: string): string {
    const methods: string[] = [];

    // status 字段
    if (resource.fields.some(f => f.name === 'status' && f.type === 'string')) {
      methods.push(`
  async updateStatus(id: number, status: string): Promise<${entityName}> {
    return this.update(id, { status } as any);
  }`);
    }

    // isActive 字段
    if (resource.fields.some(f => f.name === 'isActive' && f.type === 'boolean')) {
      methods.push(`
  async activate(id: number): Promise<${entityName}> {
    return this.update(id, { isActive: true } as any);
  }

  async deactivate(id: number): Promise<${entityName}> {
    return this.update(id, { isActive: false } as any);
  }

  async toggleActive(id: number): Promise<${entityName}> {
    const record = await this.findOne(id);
    if (!record) throw new Error('Record not found');
    return this.update(id, { isActive: !(record as any).isActive } as any);
  }`);
    }

    // deletedAt 字段（软删除）
    if (resource.fields.some(f => f.name === 'deletedAt' && f.type === 'date')) {
      methods.push(`
  async softDelete(id: number): Promise<${entityName}> {
    return this.update(id, { deletedAt: new Date() } as any);
  }

  async restore(id: number): Promise<${entityName}> {
    return this.update(id, { deletedAt: null } as any);
  }

  async findActive(options?: { select?: any; include?: any }): Promise<${entityName}[]> {
    return this.findByCondition(
      { deletedAt: null },
      { select: options?.select || this.defaultSelect, include: options?.include }
    );
  }`);
    }

    // isDeleted 字段（软删除）
    if (resource.fields.some(f => f.name === 'isDeleted' && f.type === 'boolean')) {
      methods.push(`
  async softDelete(id: number): Promise<${entityName}> {
    return this.update(id, { isDeleted: true } as any);
  }

  async restore(id: number): Promise<${entityName}> {
    return this.update(id, { isDeleted: false } as any);
  }

  async findActive(options?: { select?: any; include?: any }): Promise<${entityName}[]> {
    return this.findByCondition(
      { isDeleted: false },
      { select: options?.select || this.defaultSelect, include: options?.include }
    );
  }`);
    }

    // enabled 字段
    if (resource.fields.some(f => f.name === 'enabled' && f.type === 'boolean')) {
      methods.push(`
  async enable(id: number): Promise<${entityName}> {
    return this.update(id, { enabled: true } as any);
  }

  async disable(id: number): Promise<${entityName}> {
    return this.update(id, { enabled: false } as any);
  }`);
    }

    return methods.length > 0 ? methods.join('\n') : '';
  }

  /**
   * 转换为 PascalCase
   */
  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * 写入文件
   */
  writeFile(
    resource: ResourceDefinition,
    outputDir: string,
    overwrite: boolean = false,
  ): void {
    const repositoryDir = path.join(outputDir, resource.name);

    // 创建目录
    if (!fs.existsSync(repositoryDir)) {
      fs.mkdirSync(repositoryDir, { recursive: true });
    }

    const repositoryPath = path.join(repositoryDir, `${resource.name}.repository.ts`);
    if (!fs.existsSync(repositoryPath) || overwrite) {
      fs.writeFileSync(repositoryPath, this.generateRepository(resource));
    }
  }
}

